name: Server Coverage

on: [push, pull_request]

jobs:

  run:
    name: Server Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install dependencies
        run: |
          cd server
          npm ci

      - name: Run tests and collect coverage
        run: |
          cd server
          npm run test

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1.0.13

        with:
          file: ./server/coverage/coverage-final.json
          flags: unittest
